name: Generate Site

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  generate:
    if: github.repository_owner == 'marchof'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - run: |
        mvn --no-transfer-progress package exec:java -Dexec.mainClass=org.javabubble.generator.SiteGenerator
      working-directory: generator

    # Publish to AWS Bucket
    - uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        role-to-assume: arn:aws:iam::830482727482:role/github-workflow-javabubble
        aws-region: eu-central-1
      if: github.ref == 'refs/heads/main'
    - run: |
        aws s3 sync generator/target/site s3://javabubble.org
        aws cloudfront create-invalidation --distribution-id EH2BVKQRF4MDG --paths "/*"
      if: github.ref == 'refs/heads/main'
